; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_m4]
platform = atmelsam
board = adafruit_feather_m4
framework = arduino
monitor_speed = 115200
monitor_filters = default, time
lib_deps = 
	cnmat/OSC@^1.0.0
	arduino-libraries/Ethernet@^2.0.2
	https://github.com/marzer/tomlplusplus.git
	adafruit/SdFat - Adafruit Fork@^2.3.103
	adafruit/Adafruit SPIFlash@^5.1.1
build_unflags = -std=gnu++11
build_flags = 
	-Wall
	-Wextra
	-std=gnu++17
	-DTOML_EXCEPTIONS=0
